# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 1358bd3e6946da1cd1efb2d430b8abe45f1c772ecf8a5475ec4d879c91fbf9ddc17dbf247299468cd0a46daa8e0c7d2a9967cd82df6e86751bb1283fa8e123fd

test:
  secret_key_base: 0869f4c7ab1aeda930b81082a0fde630f7c3afe73ab3f8ff1c94669a036b6a06272ec4593ad22d03a36b1a85f899aee14dc30b35a2ae269a9688985d10a578da

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
